SoundCloud Export && Lookup
metabrainz/troi-recommendation-playground pull request #147
Opened 2024-08-06 10:54 UTC by rimma-kubanova

PR Status: In Progress

- Developed a SoundCloud API class to manage SoundCloud interactions.
- Implemented SoundCloud lookup features, including:
   - Fixes for unplayable tracks.
   - SoundCloud Labs API ID lookup.
   - Submission functionality to SoundCloud.

- [ ] test lookup functionality
- [ ] test rate limits

2024-08-22 15:31 UTC, rimma-kubanova commented
I updated this PR

* Integrated SoundCloud export (can successfully create playlists in SoundCloud and put tracks into it)

* SoundCloud lookup (still needs some tweaking, since lookup doesnt always finds songs. I guess it just needs more data to work with. OVERALL the logic is implemented)

2024-08-23 20:53 UTC, amCap1712 requested changes
The api calls should use `linked_partitioning=true` where relevant, the format of the JSON response changes if you pass the query param so be sure to test the patches again and update the code that accesses the JSON. 

You can find an example here of how to paginate with linked_partitioning: https://github.com/metabrainz/listenbrainz-server/blob/f0334debe2b003cc36a6d94765442bf3be0a34d5/listenbrainz/metadata_cache/soundcloud/handler.py#L66-L109.

2024-08-23 20:55 UTC, amCap1712 commented
Also, the code to use soundcloud export using CLI was missing. I added it myself  because I needed it for testing.

2024-08-23 20:56 UTC, amCap1712 commented on troi/tools/utils.py
> +        http = requests.Session()
Add a hook that calls `raise_for_status` automatically after the API call.

2024-08-24 04:18 UTC, rimma-kubanova commented
@amCap1712 Thanks for the feedback! Working on it. Completely forgot about cli, will add them to others then

2024-08-26 08:34 UTC, rimma-kubanova commented
@amCap1712 hi! I updated the code

2024-08-26 10:47 UTC, amCap1712 commented on troi/tools/utils.py
> +            data = response.json()
This looks wrong, track_details endpoint does not return a collection. You should create the track_data here directly from the response without any loop.

2024-08-26 10:48 UTC, amCap1712 commented on troi/tools/utils.py
> +            response.raise_for_status()
raise_for_status call is redundant here because of the hook.

2024-08-26 10:49 UTC, amCap1712 commented on troi/tools/utils.py
> +    def get_unplayable_tracks(self, playlist_id, **kwargs):
This function is almost similar to the get playlist tracks one, you can call that function here to get the tracks in the playlist and then filter the unstreamable ones and return them.

2024-08-26 10:50 UTC, amCap1712 commented on troi/tools/utils.py
> +                print(f"HTTP error occurred: {http_err}")
Create a `logger = logging.getLogger(__name__)` at the top of the file and use `logger.error` here.

2024-08-26 10:51 UTC, amCap1712 requested changes
Once these changes are done, I'll do a retest to ensure playlist exports work and then we can merge it.

2024-08-26 15:03 UTC, rimma-kubanova commented
@amCap1712 Thanks for your feedback! I've implemented all the changes you requested. 

I also made some additional tweaks and identified a few errors. The `fixup_soundcloud_playlist` function should now work properly, including handling unplayable tracks.

The only thing I'm facing is that the Labs Lookup api retrieves soundcloud ids for only a limited number of songs, which makes testing a bit difficult

2024-08-30 12:07 UTC, merged